#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# 이 저장소 안에서만 의미가 있다. 스크립트 자신의 위치에서 루트를 뽑는다.
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SITE="$REPO/web"
PROJECT_NAME="kihyun-opensource"

# vercel 이 PATH 에 있으면 그것을, 없으면 npx 로 내려받아 쓴다.
if command -v vercel >/dev/null 2>&1; then
  VERCEL=(vercel)
else
  VERCEL=(npx --yes vercel@latest)
fi

banner "Vercel 배포 준비"

# ──────────────────────────────────────────────────────────────────────────
stage "사전 점검"
say "시작하기 전에 필요한 것들이 있는지 본다."

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh    ✓ $(gh api user --jq .login 2>/dev/null || echo '인증됨')"
else
  warn "gh 가 없거나 인증되지 않았다. 'gh auth login' 을 먼저 해야 secrets 를 넣을 수 있다."
  confirm "그래도 계속할까? (마지막에 넣을 명령을 알려준다)" || exit 1
fi

say "node  ✓ $(node --version)"
say "repo  ✓ $(git -C "$REPO" remote get-url origin 2>/dev/null || echo '원격 없음')"
if command -v vercel >/dev/null 2>&1; then
  say "vercel ✓ 설치돼 있음"
else
  note "vercel CLI 는 설치돼 있지 않아 npx 로 받아 쓴다 (처음 한 번 느리다)"
fi
pause "계속하려면 Enter"

# ──────────────────────────────────────────────────────────────────────────
stage "Vercel 로그인"
say "브라우저가 열린다. 승인만 누르면 된다."
note "이미 로그인돼 있으면 곧바로 넘어간다."
printf '\n'
if "${VERCEL[@]}" whoami >/dev/null 2>&1; then
  say "이미 로그인돼 있다: $("${VERCEL[@]}" whoami 2>/dev/null | tail -1)"
else
  "${VERCEL[@]}" login
fi
pause "로그인이 끝났으면 Enter"

# ──────────────────────────────────────────────────────────────────────────
stage "프로젝트 만들기"
say "Vercel 프로젝트를 만들고 이 저장소의 web/ 에 연결한다."
warn "대시보드에서 import 하지 않는다. Git 을 연결하면 Vercel 이 푸시마다"
warn "자기 환경에서 빌드하는데, 거기엔 Flutter 가 없어 데모 없는 사이트가 나간다."
printf '\n'
say "프로젝트 이름을 kihyun-opensource 로 못 박고 만든다."
note "이름을 인자로 주기 때문에 '어느 프로젝트?' 같은 목록이 뜨지 않는다."
note "계정에 팀이 여럿이면 어느 스코프인지만 한 번 물을 수 있다."
printf '\n'
pause "준비됐으면 Enter"
printf '\n'

cd "$SITE"
if [[ -f .vercel/project.json ]]; then
  say "이미 연결돼 있다. 다시 만들지 않는다."
elif ! "${VERCEL[@]}" link --yes --project "$PROJECT_NAME"; then
  # --yes 가 통하지 않는 경우(스코프 선택이 필요하다든지)에는 대화형으로 넘긴다.
  warn "자동 연결이 실패했다. 대화형으로 진행한다."
  note "'Link to existing project?' 에는 N, 이름에는 $PROJECT_NAME 을 답하라."
  printf '\n'
  "${VERCEL[@]}" link
fi

if [[ ! -f .vercel/project.json ]]; then
  warn "연결에 실패했다 (.vercel/project.json 이 없다). 다시 실행해 보라."
  exit 1
fi

# link 는 GitHub 저장소를 자동으로 붙인다. 그대로 두면 푸시마다 Vercel 이
# 자기 환경에서 빌드하는데, 거기엔 Flutter 가 없어 데모 없는 사이트가 나가고
# Actions 가 올린 정상 배포와 경쟁한다. 배포는 Actions 한 곳에서만 한다.
printf '\n'
say "Vercel 쪽 자동 빌드를 끊는다 (배포는 Actions 만 한다)..."
"${VERCEL[@]}" git disconnect --yes >/dev/null 2>&1 \
  && say "  ✓ Git 연결 해제됨" \
  || note "  이미 연결돼 있지 않다"

VERCEL_ORG_ID=$(node -p "require('./.vercel/project.json').orgId")
VERCEL_PROJECT_ID=$(node -p "require('./.vercel/project.json').projectId")
cd "$REPO"

say ""
say "orgId      $VERCEL_ORG_ID"
say "projectId  $VERCEL_PROJECT_ID"
note "web/.vercel/ 은 .gitignore 대상이라 커밋되지 않는다."
pause "계속하려면 Enter"

# ──────────────────────────────────────────────────────────────────────────
stage "액세스 토큰 발급"
say "Actions 가 Vercel 에 배포하려면 토큰이 필요하다."
note "푸시 배포는 Vercel 이 자기 안에서 하는 일이라 토큰이 없지만,"
note "우리는 빌드를 Actions 로 가져왔기 때문에 바깥에서 인증해야 한다."
printf '\n'
open_url "https://vercel.com/account/tokens"
step "좌상단 스코프 선택기가 '개인 계정'인지 확인한다 (팀이면 이 페이지가 안 보인다)."
step "이름을 적는다 — 예: kihyun-opensource-ci"
step "Scope 드롭다운에서 팀을 고르고, 그 안에서 방금 만든 kihyun-opensource 프로젝트를 고른다."
note "'All Projects' 를 고르면 팀 전체 토큰이 된다. 프로젝트 하나로 좁히는 편이 안전하다."
step "만료를 고르고 Create 를 누른다."
step "값을 복사한다. vcp_ 로 시작하고, 이 화면을 떠나면 다시 볼 수 없다."
printf '\n'
ask_secret VERCEL_TOKEN "토큰을 붙여넣어라 (화면에 보이지 않는다):"

if [[ -z "${VERCEL_TOKEN:-}" ]]; then
  warn "토큰이 비어 있다. 다시 실행해 보라."
  exit 1
fi

# ──────────────────────────────────────────────────────────────────────────
stage "GitHub secrets 기록과 검증"
say "세 값을 저장소 secrets 에 넣는다."
printf '\n'
set_secret VERCEL_TOKEN "$VERCEL_TOKEN"
set_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"

printf '\n'
say "토큰이 실제로 그 프로젝트에 닿는지 확인한다..."
if curl -sf -o /dev/null \
     -H "Authorization: Bearer $VERCEL_TOKEN" \
     "https://api.vercel.com/v9/projects/$VERCEL_PROJECT_ID"; then
  printf '  %s✓%s 토큰으로 프로젝트를 읽을 수 있다.\n' "$GREEN" "$RESET"
else
  warn "토큰으로 프로젝트를 읽지 못했다."
  note "스코프가 다른 프로젝트로 잡혔거나 값을 잘못 붙여넣었을 수 있다."
  note "https://vercel.com/account/tokens 에서 다시 만들고 이 스크립트를 다시 돌려라."
  SKIPPED+=("VERCEL_TOKEN 검증 실패 — 토큰 스코프를 확인할 것")
fi

pause "계속하려면 Enter"
finish

note "다음: 배포 워크플로가 이 secrets 를 읽는다."
note "이 스크립트는 한 번 쓰고 지워도 된다 — 값은 전부 GitHub 에 들어갔다."
printf '\n'
